name: CI/CD Pipeline

on:
  push:
    branches:
      - main # sirf main branch pe push hoga to ye chalega

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-react-app:latest \
                       -t ${{ secrets.DOCKERHUB_USERNAME }}/my-react-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-react-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-react-app:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/react-app-deployment \
            react-app-container=${{ secrets.DOCKERHUB_USERNAME }}/my-react-app:latest
          kubectl rollout status deployment/react-app-deployment
